# Generated by Django 5.0.4 on 2024-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('streetaddress', models.CharField(max_length=255)),
                ('streetaddress2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('stateprovince', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('hearaboutus', models.CharField(choices=[('from social media', 'From social media'), ('recommended by someone', 'Recommended by someone'), ('just happended to find it', 'Just happended to find it')], max_length=100)),
                ('suggestion', models.CharField(max_length=255)),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10)),
                ('twofullname1', models.CharField(max_length=255)),
                ('twofullname2', models.CharField(max_length=255)),
                ('twoaddress1', models.CharField(max_length=255)),
                ('twoaddress2', models.CharField(max_length=255)),
                ('twocontact1', models.CharField(max_length=255)),
                ('twocontact2', models.CharField(max_length=255)),
            ],
        ),
    ]
