# Generated by Django 5.0.4 on 2024-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0002_customerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='feedback',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
