# Generated by Django 5.0.4 on 2024-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0003_customerdetails_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='feedback',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='suggestion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twoaddress1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twoaddress2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twocontact1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twocontact2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twofullname1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='twofullname2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
