# Generated by Django 5.0.4 on 2024-05-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0005_remove_todo_id_todo_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='customerid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
