# Generated by Django 5.0.4 on 2024-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0006_remove_customerdetails_id_customerdetails_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
